services:
  - type: web
    name: boca-bot
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: BOCA_HEADLESS
        value: 1
      - key: BOCA_EMAIL
        sync: false
      - key: BOCA_PASSWORD
        sync: false
