services:
  - type: web
    name: boca-bot
    env: docker
    plan: free
    envVars:
      - key: BOCA_EMAIL
        sync: false
      - key: BOCA_PASSWORD
        sync: false
      - key: BOCA_CANTIDAD_ENTRADAS
        sync: false
      - key: PORT
        value: 5000